#!/usr/bin/env bun
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";

interface ModuleRow {
  source: string;
  tests: string[];
  fake: string | null;
  contract: string | null;
}

const outputPath = "docs/architecture-map.md";

const walk = (dir: string): string[] => {
  if (!existsSync(dir)) {
    return [];
  }
  const entries = readdirSync(dir, { withFileTypes: true });
  const paths: string[] = [];
  for (const entry of entries) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      paths.push(...walk(path));
    } else if (entry.isFile()) {
      paths.push(path);
    }
  }
  return paths.sort();
};

const toPosix = (path: string): string => path.split(sep).join("/");
const rel = (path: string): string => toPosix(relative(process.cwd(), path));
const withoutSuffix = (value: string, suffix: string): string =>
  value.endsWith(suffix) ? value.slice(0, -suffix.length) : value;

const collectRows = (): ModuleRow[] => {
  const sourceFiles = walk("src")
    .filter(path => path.endsWith(".ts"))
    .filter(path => !path.endsWith(".d.ts"));
  const testFiles = walk("test").filter(path => path.endsWith(".test.ts"));
  const fakeFiles = new Map(
    walk("test/fakes")
      .filter(path => path.endsWith(".ts"))
      .map(path => [withoutSuffix(path.split("/").pop() ?? "", ".ts").replace(/^Fake/, ""), rel(path)])
  );
  const contractFiles = new Map(
    walk("test/contracts")
      .filter(path => path.endsWith("Contract.ts"))
      .map(path => [withoutSuffix(path.split("/").pop() ?? "", "Contract.ts"), rel(path)])
  );

  return sourceFiles.map(source => {
    const base = withoutSuffix(source.split("/").pop() ?? "", ".ts");
    const sourceRel = rel(source);
    const expectedTestSuffix = `${withoutSuffix(sourceRel.replace(/^src\//, "test/"), ".ts")}.test.ts`;
    const matchingTests = testFiles
      .map(rel)
      .filter(test => test === expectedTestSuffix || test.endsWith(`/${base}.test.ts`));
    return {
      source: sourceRel,
      tests: matchingTests,
      fake: fakeFiles.get(base) ?? null,
      contract: contractFiles.get(base) ?? null,
    };
  });
};

const collectAdrRows = (): string[] =>
  walk("docs/adr")
    .filter(path => path.endsWith(".md"))
    .map(rel);

const render = (): string => {
  const rows = collectRows();
  const adrs = collectAdrRows();
  const lines = [
    "# Architecture Map",
    "",
    "Generated by `bun run docs:architecture`. Keep this file committed so agents have a compact, current map of the repository.",
    "",
    "## Source Map",
    "",
    "| Source | Tests | Fake | Contract |",
    "| --- | --- | --- | --- |",
  ];

  for (const row of rows) {
    lines.push(`| \`${row.source}\` | ${row.tests.map(test => `\`${test}\``).join("<br>") || "-"} | ${row.fake ? `\`${row.fake}\`` : "-"} | ${row.contract ? `\`${row.contract}\`` : "-"} |`);
  }

  lines.push("", "## ADRs", "");
  for (const adr of adrs) {
    lines.push(`- \`${adr}\``);
  }
  lines.push("");
  return lines.join("\n");
};

const main = (): number => {
  const check = process.argv.includes("--check");
  const next = render();
  if (check) {
    const current = existsSync(outputPath) ? readFileSync(outputPath, "utf8") : "";
    if (current !== next) {
      console.error(`${outputPath} is stale. Run 'bun run docs:architecture'.`);
      return 1;
    }
    console.log(`OK: ${outputPath} is current`);
    return 0;
  }
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, next);
  console.log(`Wrote ${outputPath}`);
  return 0;
};

process.exit(main());
